[colors.normal]
black = "#000000"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#292D3E"
foreground = "#A6ACCD"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"
