use_nerdfont=true
audio_backend="pulseaudio"
#backend_device="HyperX Cloud Alpha Wireless Analog Stereo"
backend_device="alsa_output.usb-HP__Inc_HyperX_Cloud_Alpha_Wireless_00000001-00.analog-stereo"
