[[language]]
name = 'rust'

[language-server.rust-analyzer.config.check]
command = "clippy"

# Based on instructions found at https://github.com/helix-editor/helix/wiki/Debugger-Configurations#rust
[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /usr/local/etc/lldb_vscode_rustc_primer.py" ] }